[workspace]
resolver = "2"

members = ["actix", "gkvocabdb"]
default-members = ["actix"]

[workspace.package]
version = "0.1.6"
edition = "2021"
authors = ["Jeremy March <jmarch@gradcenter.cuny.edu>"]

[profile.release]
opt-level = 3
lto = true
