[package]
name = "gkvocabdb"
version = "0.2.0"
edition = "2021"
authors = ["Jeremy March <jmarch@gradcenter.cuny.edu>"]
license = "AGPL-3.0"

[lib]
name = "gkvocabdb"
path = "src/lib.rs"
doctest = false

[dependencies]
quick-xml = "0.30.0"
unicode-normalization = { version = "0.1.22", default-features = false }
chrono = { version = "0.4.30", default-features = false, features=["clock"] }
sqlx = { version = "0.7.2", features = ["sqlite", "runtime-tokio-rustls", "any", "macros"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"
regex = "1.9.5"
csv = "1.2.2"

[dev-dependencies]
tokio = { version = "1.32.0", features = ["rt", "macros"] }

[profile.release]
opt-level = 3
lto = true
