[package]
name = "actix"
version = "0.2.0"
edition = "2021"
authors = ["Jeremy March <jmarch@gradcenter.cuny.edu>"]
license = "AGPL-3.0"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
gkvocabdb = { path = "../gkvocabdb" }
actix-web = { version = "4.4.0" }
actix-files = "0.6.2"
actix-session = { version = "0.8.0", features = ["cookie-session"] }
actix-multipart = "0.6.1"
actix-web-httpauth = "0.8.0"

quick-xml = "0.30.0"

unicode-normalization = { version = "0.1.22", default-features = false }

chrono = { version = "0.4.30", default-features = false, features=["clock"] }

sqlx = { version = "0.7.2", features = ["sqlite", "runtime-tokio-rustls", "any", "macros"] }

serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"
futures = "0.3.28"
env_logger = "0.10.0"
thiserror = "1.0.48"
secrecy = { version = "0.8", features = ["serde"] }
hex = "0.4.3"

regex = "1.9.5"
percent-encoding = "2.3.0"
csv = "1.2.2"

[dev-dependencies]
actix-rt = "2.9.0"

[profile.release]
opt-level = 3
#lto = true
